name: Build packages

on:
  push:

  schedule:
    - cron:  '0 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Update submodules
      run: git submodule foreach git pull origin master

    - uses: stefanzweifel/git-auto-commit-action@v2.3.0
      name: Commit updates
      with:
        commit_message: Update submodules
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Copy repository
      run: sudo cp -R ${PWD} /repo
      
    - name: Create temporary packages directory
      run: mkdir /tmp/packages
      
    - name: Change ownership
      run: sudo chown 1000:1000 -R /repo /tmp/packages
      
    - name: Build packages
      run: docker run -v /tmp/packages:/tmp/packages -v /repo:/build -w /build --user arched chrisnharvey/arched /build/build.sh
        
    - name: Copy built packages back into repository directory
      run: sudo cp -R /tmp/packages ${PWD}
        
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
        AWS_S3_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
        SOURCE_DIR: packages
