name: Build packages

on:
  push:

  schedule:
    - cron:  '0 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build packages
      run: docker run -it -v /tmp/packages:/tmp/packages -v ${PWD}:/build -w /build --user arched chrisnharvey/arched /build/build.sh
   
    - uses: actions/upload-artifact@master
      with:
        name: packages
        path: /tmp/packages
