name: Update submodules

on:
  push:

  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Update submodules
      run: git submodule foreach git pull origin master

    - uses: stefanzweifel/git-auto-commit-action@v2.3.0
      name: Commit updates
      with:
        commit_message: Update submodules
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
